# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('cpf', models.TextField(max_length=11)),
                ('descrition', models.TextField(blank=True, max_length=100, null=True)),
                ('firebase_token', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
